version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8020
    volumes:
      - .:/app
      - ./data:/app/db
    ports:
      - "8020:8020"
    networks:
      - dental_network

volumes:
  data:

networks:
  dental_network:
    driver: bridge
